# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a9cf5ca651cf3b32230617c1dbe02dff891cb293e320a4ee9492b23d3055851c8b7826baef599093505529a15cfe757b6ac27cf6b685c35bb2ce3749d6a8e36

test:
  secret_key_base: 75c737816b52c1a38b439fbbe70d73a1f0b2dfa4ebd7e2eef24d7088c6e5fb1b540fba25e7e5b01e7d87380d8394d39c9ddadebc148063366fee23c5cf9cb58a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
